### ISSUE TITLE
Ability to request for time-offs and their moderation

### ISSUE THREAD

**Issue by faridnsh** [jordanwalsh23/hubot-bamboohr#2]
Hi there,

I'm going to work on these features and hopefully be able to merge it back here. I'd love to know if you have any preferences how they should be implemented.

**Comment by jordanwalsh23** [comment]
Hi. This is actually an inactive project for me. If you would like me to transfer ownership to you, I'm happy to.

**Comment by faridnsh** [comment]
Sure. That would work as well. :smile:

**Comment by faridnsh** [comment]
I actually decided to put the extra stuff into their own separate modules, in case people don't like to have them and just have the specific ones. Feel free to reopen this if you disagree.
